const express = require('express');
const router = express.Router();

// Import module routes
const authRoutes = require('../modules/auth/auth.routes');
const userRoutes = require('../modules/user/user.routes');
const productRoutes = require('../modules/product/product.routes');
const bannerRoutes = require('../modules/banner/banner.routes');
const birthstoneRoutes = require('../modules/birthstone/birthstone.routes');
const appointmentRoutes = require('../modules/appointment/appointment.routes');
const caratWeightRoutes = require('../modules/caratWeight/caratWeight.routes');
const categoryRoutes = require('../modules/category/category.routes');
const centerDiamondPriceRoutes = require('../modules/centerDiamondPrice/centerDiamondPrice.routes');
const codSequenceRoutes = require('../modules/codSequence/codSequence.routes');
const couponRoutes = require('../modules/coupon/coupon.routes');
const custJewelleryBeforeAfterRoutes = require('../modules/custJewelleryBeforeAfter/custJewelleryBeforeAfter.routes');
const customInquiryRoutes = require('../modules/customInquiry/customInquiry.routes');
const diamondRoutes = require('../modules/diamond/diamond.routes');
const diamondClarityRoutes = require('../modules/diamondClarity/diamondClarity.routes');
const diamondColorRoutes = require('../modules/diamondColor/diamondColor.routes');
const diamondCutRoutes = require('../modules/diamondCut/diamondCut.routes');
const diamondPriceRoutes = require('../modules/diamondPrice/diamondPrice.routes');
const diamondPriceNewRoutes = require('../modules/diamondPriceNew/diamondPriceNew.routes');
const diamondShapeRoutes = require('../modules/diamondShape/diamondShape.routes');
const diamondSizeRoutes = require('../modules/diamondSize/diamondSize.routes');
const diamondTypeRoutes = require('../modules/diamondType/diamondType.routes');
const featuredRoutes = require('../modules/featured/featured.routes');
const footerSettingsRoutes = require('../modules/footerSettings/footerSettings.routes');
const instagramPostRoutes = require('../modules/instagramPost/instagramPost.routes');
const menuItemRoutes = require('../modules/menuItem/menuItem.routes');
const menuSectionRoutes = require('../modules/menuSection/menuSection.routes');
const metalColorRoutes = require('../modules/metalColor/metalColor.routes');
const metalPurityRoutes = require('../modules/metalPurity/metalPurity.routes');
const metalTypeRoutes = require('../modules/metalType/metalType.routes');
const ringSizeRoutes = require('../modules/ringSize/ringSize.routes');
const sideDiamondPriceRoutes = require('../modules/sideDiamondPrice/sideDiamondPrice.routes');
const sieveSizeRoutes = require('../modules/sieveSize/sieveSize.routes');
const sizeRoutes = require('../modules/size/size.routes');
const vtoMasterRoutes = require('../modules/vtoMaster/vtoMaster.routes');
const notificationRoutes = require('../modules/notification/notification.routes');
const uploadRoutes = require('../modules/upload/upload.routes');
const reviewRoutes = require('../modules/review/review.routes');
const settingRoutes = require('../modules/setting/setting.routes');

// Mount routes
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/products', productRoutes);
router.use('/banners', bannerRoutes);
router.use('/birthstones', birthstoneRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/carat-weights', caratWeightRoutes);
router.use('/categories', categoryRoutes);
router.use('/center-diamond-prices', centerDiamondPriceRoutes);
router.use('/cod-sequences', codSequenceRoutes);
router.use('/coupons', couponRoutes);
router.use('/cust-jewellery-before-after', custJewelleryBeforeAfterRoutes);
router.use('/custom-inquiries', customInquiryRoutes);
router.use('/diamonds', diamondRoutes);
router.use('/diamond-clarities', diamondClarityRoutes);
router.use('/diamond-colors', diamondColorRoutes);
router.use('/diamond-cuts', diamondCutRoutes);
router.use('/diamond-prices', diamondPriceRoutes);
router.use('/diamond-prices-new', diamondPriceNewRoutes);
router.use('/diamond-shapes', diamondShapeRoutes);
router.use('/diamond-sizes', diamondSizeRoutes);
router.use('/diamond-types', diamondTypeRoutes);
router.use('/featured', featuredRoutes);
router.use('/footer-settings', footerSettingsRoutes);
router.use('/instagram-posts', instagramPostRoutes);
router.use('/menu-items', menuItemRoutes);
router.use('/menu-sections', menuSectionRoutes);
router.use('/metal-colors', metalColorRoutes);
router.use('/metal-purities', metalPurityRoutes);
router.use('/metal-types', metalTypeRoutes);
router.use('/ring-sizes', ringSizeRoutes);
router.use('/side-diamond-prices', sideDiamondPriceRoutes);
router.use('/sieve-sizes', sieveSizeRoutes);
router.use('/sizes', sizeRoutes);
router.use('/vto-masters', vtoMasterRoutes);
router.use('/notifications', notificationRoutes);
router.use('/upload', uploadRoutes);
router.use('/reviews', reviewRoutes);
router.use('/settings', settingRoutes);

module.exports = router;
